Add new regions and update names for old regions
passlickdev/r6regionchanger pull request #2
Opened 2020-06-06 07:17 UTC by danielwerg

2020-07-26 04:12 UTC, danielwerg commented
Any update? Is this still maintained?

2020-07-26 08:48 UTC, passlickdev commented
> Any update? Is this still maintained?

Thanks for your contribution. Unfortunately, I don't have enough time to validate the changes right now, but this will happen in August. Sorry for the delay.

2020-08-10 18:09 UTC, npasslick requested changes
@danielwerg Please review the change requests in order for the software to work

2020-08-10 18:09 UTC, npasslick commented on src/R6RegionChanger/frmMain.vb
> +                dropRegion.Text = "japanwest (japan west)"
@danielwerg `R6ProfileRegionVar` represents the content of the `DataCenterHint` setting in the INI. If the `DataCenterHint` needs to be `playfab/[region]`, this should be reflected in the conditions (same for default).

Also, the `dropRegion.Text` is case-sensitive. The string should be the same as in the droplist, otherwise it will not work (e.g. `westeurope (europe west)` -> `westeurope (Europe West)`)

 #2

2020-08-10 18:09 UTC, npasslick commented on src/R6RegionChanger/frmMain.vb
>              btnApply.Enabled = False
@danielwerg See above #2

2020-08-10 18:09 UTC, passlickdev commented on src/R6RegionChanger/clsScript.vb
> +                    MessageBox.Show("Settings saved successfully!" & vbNewLine & vbNewLine & "Profile: " & frmMain.dropProfile.Text & vbNewLine & "Region: southafricanorth (africa south north)" & vbN
@danielwerg `dropRegion.Text` is case-sensitive, this does not work (string in droplist and in this elif condition are not the same).

The string in the MsgBox for the region should reflect the string in the droplist.

#2

2022-08-30 19:01 UTC, closed without merging